### ISSUE TITLE
I wonder how you make jni_prefix.patch for another webrtc ver.

### ISSUE THREAD

**Issue by KimSeongHeon** [webrtc-sdk/webrtc-build#20]
Hi, I'm really thanksful your repo.
It is very helpful for me. Thank you.

I wonder that how you make `jni_prefix.patch` file for changing android package name.
I'm very interested in making build for another webrtc version(m120).
But too many files in webrtc was changed. so `jni_prefix.patch` doesn't  be affected in other version(m120).
I want to learn how you make `jni_prefix.patch` file and I'll make another `jni_prefix.patch` and share it.

Thank you so much. Please give me your thought 👍

**Comment by davidliu** [comment]
There's not really much to explain here, as there isn't a process to making the prefix patch, just trial and error until everything is prefixed. The current jni_prefix patch is now on m125, but how to update it for another version is completely up to how the upstream changes between versions. Your best bet is to look at the current prefix patch and figure out how to adapt it for whichever version you need.
